library(janitor)
library(stats)
library(hash)
library(caret)
library(glmnet)
library(car)
library(Metrics)
library(targets)
library(regPackage1)
library(dplyr)
library(ggplot2)
library(pROC)
library(randomForest)
library(regPackage1)

data("insurance_train")
data("insurance_test")

source("./R/functions.R")
source("./R/glmnet_fit_hmd.R")
source("./R/glmnet_predict_hmd.R")
source("./R/rf_fit_hmd.R")
source("./R/rf_predict_hmd.R")
