library(janitor)
library(stats)
library(hash)
library(caret)
library(glmnet)
library(car)
library(Metrics)
library(targets)
library(regPackage1)
library(dplyr)
library(ggplot2)
library(pROC)

data("insurance_test")
